import Link from 'next/link';
import { ArrowUpRight, FileText, Plus, Trash2 } from 'lucide-react';
import { deleteResourceAction, toggleResourceAction } from '@/app/admin/actions';
import { ConfirmSubmit } from '@/components/admin/ConfirmSubmit';
import { StorageUsage } from '@/components/admin/StorageUsage';
import { db } from '@/lib/db';

export default async function MaterialsAdminPage({ searchParams }: { searchParams: Promise<{ saved?: string }> }) {
  const [items, params, mediaUsage] = await Promise.all([db.resource.findMany({ include: { media: true }, orderBy: { position: 'asc' } }), searchParams, db.media.aggregate({ _sum: { size: true } })]);
  return <><header className="admin-topbar"><div><h1>Arquivos e materiais</h1><p>Gerencie os PDFs públicos para download.</p></div><Link className="primary-button" href="/admin/materiais/new"><Plus size={16} /> Novo PDF</Link></header><div className="admin-content">{params.saved ? <div className="flash">Alterações salvas com sucesso.</div> : null}<StorageUsage usedBytes={mediaUsage._sum.size ?? 0} /><section className="admin-card"><div className="admin-card-header"><div><h2>Materiais publicados</h2><p>{items.length} arquivo{items.length === 1 ? '' : 's'} cadastrado{items.length === 1 ? '' : 's'}.</p></div></div>{items.length ? <table className="admin-table"><thead><tr><th>Arquivo</th><th>Nome</th><th>Status</th><th>Ações</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><span className="document-table-icon"><FileText size={17} /> PDF</span></td><td><strong>{item.title}</strong><small>{item.media.originalName}</small></td><td><span className={item.enabled ? 'status-pill' : 'status-pill pending'}>{item.enabled ? 'ATIVO' : 'OCULTO'}</span></td><td><div className="table-actions"><Link className="button-link" href={`/admin/materiais/${item.id}`}>Editar <ArrowUpRight size={14} /></Link><form className="inline-form" action={toggleResourceAction}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="enabled" value={String(!item.enabled)} /><button className="secondary-button" type="submit">{item.enabled ? 'Ocultar' : 'Exibir'}</button></form><form className="inline-form" action={deleteResourceAction}><input type="hidden" name="id" value={item.id} /><ConfirmSubmit><Trash2 size={14} /></ConfirmSubmit></form></div></td></tr>)}</tbody></table> : <div className="empty-state">Nenhum PDF publicado ainda.</div>}</section></div></>;
}
