import { deleteStatAction, saveAboutAction, createStatAction, updateStatAction } from '@/app/admin/actions';
import { ConfirmSubmit } from '@/components/admin/ConfirmSubmit';
import { ImageUploader } from '@/components/admin/ImageUploader';
import { db } from '@/lib/db';

export default async function AboutAdminPage({ searchParams }: { searchParams: Promise<{ saved?: string }> }) {
  const [about, stats, params] = await Promise.all([db.aboutSection.findUniqueOrThrow({ where: { id: 'default' } }), db.aboutStat.findMany({ orderBy: { position: 'asc' } }), searchParams]);
  return <><header className="admin-topbar"><div><h1>Sobre</h1><p>Edite a apresentação e os indicadores do artista.</p></div></header><div className="admin-content">{params.saved ? <div className="flash">Alterações salvas com sucesso.</div> : null}<form action={saveAboutAction} className="admin-card"><div className="admin-card-header"><div><h2>Conteúdo Sobre</h2><p>Título, corpo e fotografia são campos separados.</p></div></div><div className="form-grid"><div className="field"><label>Título da seção</label><input name="title" defaultValue={about.title} required /></div><label className="toggle-line"><input type="checkbox" name="enabled" defaultChecked={about.enabled} /> Exibir seção no site</label><div className="field full"><label>Texto</label><textarea name="body" defaultValue={about.body} required /></div></div><div className="admin-section"><ImageUploader name="imageUrl" current={about.imageUrl} label="Imagem da seção" /></div><div className="form-actions"><button className="primary-button" type="submit">Salvar alterações</button></div></form><section className="admin-card admin-section"><div className="admin-card-header"><div><h2>Estatísticas</h2><p>Os indicadores são editáveis, ordenáveis e podem ser ocultados.</p></div></div><div className="admin-table">{stats.map((stat) => <div className="stat-admin-row" key={stat.id}><form className="stat-admin-edit" action={updateStatAction}><input type="hidden" name="id" value={stat.id} /><input name="value" defaultValue={stat.value} aria-label="Valor" /><input name="label" defaultValue={stat.label} aria-label="Rótulo" /><label className="toggle-line"><input type="checkbox" name="enabled" defaultChecked={stat.enabled} /> Exibir</label><button className="primary-button" type="submit">Salvar</button></form><form action={deleteStatAction}><input type="hidden" name="id" value={stat.id} /><ConfirmSubmit><span>Excluir</span></ConfirmSubmit></form></div>)}</div><form action={createStatAction} className="stat-admin-row new-stat"><input name="value" placeholder="10+" required /><input name="label" placeholder="ANOS" required /><label className="toggle-line"><input type="checkbox" name="enabled" defaultChecked /> Exibir</label><button className="secondary-button" type="submit">Adicionar</button></form></section></div></>;
}
