import { createAgendaAction, updateAgendaAction } from '@/app/admin/actions';

type AgendaItem = { id: string; eventDate: Date; title: string; venue: string; city: string; state: string; country: string; status: string; ticketUrl: string | null; enabled: boolean };

export function AgendaForm({ item }: { item?: AgendaItem }) {
  const action = item ? updateAgendaAction : createAgendaAction;
  const date = item ? new Date(item.eventDate).toISOString().slice(0, 16) : '';
  return <form action={action} className="admin-card"><div className="admin-card-header"><div><h2>{item ? 'Editar compromisso' : 'Novo compromisso'}</h2><p>Datas antigas saem automaticamente da área pública sem serem apagadas.</p></div></div>{item ? <input type="hidden" name="id" value={item.id} /> : null}<div className="form-grid three"><div className="field"><label>Data e hora</label><input name="eventDate" type="datetime-local" defaultValue={date} required /></div><div className="field"><label>Evento</label><input name="title" defaultValue={item?.title} required /></div><div className="field"><label>Status</label><select name="status" defaultValue={item?.status ?? 'CONFIRMADO'}><option>CONFIRMADO</option><option>A CONFIRMAR</option><option>CANCELADO</option></select></div><div className="field"><label>Local</label><input name="venue" defaultValue={item?.venue} required /></div><div className="field"><label>Cidade</label><input name="city" defaultValue={item?.city} required /></div><div className="field"><label>Estado</label><input name="state" defaultValue={item?.state} required /></div><div className="field"><label>País</label><input name="country" defaultValue={item?.country ?? 'Brasil'} required /></div><div className="field"><label>URL de ingresso</label><input name="ticketUrl" defaultValue={item?.ticketUrl ?? ''} /></div><label className="toggle-line"><input type="checkbox" name="enabled" defaultChecked={item?.enabled ?? true} /> Exibir no site</label></div><div className="form-actions"><button className="primary-button" type="submit">Salvar compromisso</button></div></form>;
}
