import { createEventAction, updateEventAction } from '@/app/admin/actions';
import { ImageUploader } from '@/components/admin/ImageUploader';
import { MultiImageUploader } from '@/components/admin/MultiImageUploader';

type EventItem = { id: string; title: string; subtitle: string; description: string; eventDate: Date; city: string; state: string; coverImage: string; enabled: boolean; images?: Array<{ imageUrl: string }> };

export function EventForm({ item }: { item?: EventItem }) {
  const action = item ? updateEventAction : createEventAction;
  return <form action={action} className="admin-card"><div className="admin-card-header"><div><h2>{item ? 'Editar evento' : 'Novo evento'}</h2><p>Organize a imagem principal e os dados do registro.</p></div></div>{item ? <input type="hidden" name="id" value={item.id} /> : null}<div className="form-grid"><div className="field"><label>Título</label><input name="title" defaultValue={item?.title} required /></div><div className="field"><label>Subtítulo</label><input name="subtitle" defaultValue={item?.subtitle ?? 'REGISTROS RECENTES'} required /></div><div className="field"><label>Data</label><input name="eventDate" type="datetime-local" defaultValue={item ? new Date(item.eventDate).toISOString().slice(0, 16) : ''} required /></div><div className="field"><label>Cidade</label><input name="city" defaultValue={item?.city} required /></div><div className="field"><label>Estado</label><input name="state" defaultValue={item?.state} required /></div><label className="toggle-line"><input type="checkbox" name="enabled" defaultChecked={item?.enabled ?? true} /> Exibir no site</label><div className="field full"><label>Descrição</label><textarea name="description" defaultValue={item?.description} /></div></div><div className="admin-section"><ImageUploader name="coverImage" current={item?.coverImage ?? '/uploads/lent-original.jpg'} label="Imagem de capa" /></div><div className="admin-section"><label className="field"><span>Galeria de miniaturas</span><MultiImageUploader name="galleryImages" current={item?.images?.map((image) => image.imageUrl) ?? []} /></label></div><div className="form-actions"><button className="primary-button" type="submit">Salvar evento</button></div></form>;
}
