import { createSetAction, updateSetAction } from '@/app/admin/actions';
import { ImageUploader } from '@/components/admin/ImageUploader';

type SetItem = { id: string; title: string; subtitle: string; genre: string; duration: string; platform: string; coverImage: string; embedUrl: string | null; externalUrl: string | null; enabled: boolean };

export function SetForm({ item }: { item?: SetItem }) {
  const action = item ? updateSetAction : createSetAction;
  return <form action={action} className="admin-card"><div className="admin-card-header"><div><h2>{item ? 'Editar set' : 'Novo set'}</h2><p>Sets do SoundCloud exibem uma prévia automática na home. O navegador pode exigir interação para liberar o áudio.</p></div></div>{item ? <input type="hidden" name="id" value={item.id} /> : null}<div className="form-grid three"><div className="field"><label>Título</label><input name="title" defaultValue={item?.title} required /></div><div className="field"><label>Subtítulo</label><input name="subtitle" defaultValue={item?.subtitle ?? 'MIX SESSION'} required /></div><div className="field"><label>Gênero</label><input name="genre" defaultValue={item?.genre} required /></div><div className="field"><label>Duração</label><input name="duration" defaultValue={item?.duration} placeholder="1:05:12" required /></div><div className="field"><label>Plataforma</label><select name="platform" defaultValue={item?.platform ?? 'SoundCloud'}><option>SoundCloud</option><option>Mixcloud</option><option>YouTube</option><option>Spotify</option><option>Link externo</option></select></div><label className="toggle-line"><input type="checkbox" name="enabled" defaultChecked={item?.enabled ?? true} /> Exibir no site</label><div className="field"><label>URL da prévia SoundCloud</label><input name="embedUrl" defaultValue={item?.embedUrl ?? ''} placeholder="https://soundcloud.com/..." /><small>Cole o link público do set ou uma URL de player do SoundCloud.</small></div><div className="field"><label>URL externa</label><input name="externalUrl" defaultValue={item?.externalUrl ?? ''} /></div></div><div className="admin-section"><ImageUploader name="coverImage" current={item?.coverImage ?? '/uploads/lent-original.jpg'} label="Capa" /></div><div className="form-actions"><button className="primary-button" type="submit">Salvar set</button></div></form>;
}
