import Link from 'next/link';
import { ArrowUpRight, Plus, Trash2 } from 'lucide-react';
import { deleteAgendaAction, saveSectionAction, toggleAgendaAction } from '@/app/admin/actions';
import { ConfirmSubmit } from '@/components/admin/ConfirmSubmit';
import { db } from '@/lib/db';

export default async function AgendaAdminPage({ searchParams }: { searchParams: Promise<{ saved?: string }> }) {
  const [items, section, params] = await Promise.all([db.agendaItem.findMany({ orderBy: [{ eventDate: 'asc' }, { position: 'asc' }] }), db.sectionSettings.findUniqueOrThrow({ where: { section: 'agenda' } }), searchParams]);
  return <><header className="admin-topbar"><div><h1>Agenda</h1><p>Próximos compromissos publicados no site.</p></div><Link className="primary-button" href="/admin/agenda/new"><Plus size={16} /> Novo compromisso</Link></header><div className="admin-content">{params.saved ? <div className="flash">Alterações salvas com sucesso.</div> : null}<form action={saveSectionAction} className="admin-card"><input type="hidden" name="section" value="agenda" /><div className="admin-card-header"><div><h2>Texto da seção</h2><p>O grid e a composição permanecem protegidos.</p></div></div><div className="form-grid three"><div className="field"><label>Título</label><input name="title" defaultValue={section.title} required /></div><div className="field"><label>Subtítulo</label><input name="subtitle" defaultValue={section.subtitle} required /></div><div className="field"><label>CTA</label><input name="cta" defaultValue={section.cta} required /></div></div><div className="form-actions"><button className="primary-button" type="submit">Salvar alterações</button></div></form><section className="admin-card admin-section"><div className="admin-card-header"><div><h2>Compromissos</h2><p>{items.length} itens cadastrados.</p></div></div><table className="admin-table"><thead><tr><th>Data</th><th>Evento</th><th>Local</th><th>Status</th><th>Ações</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short', year: 'numeric' }).format(item.eventDate).replace('.', '')}</td><td><strong>{item.title}</strong></td><td>{item.venue}<small>{item.city} / {item.state}</small></td><td><span className={item.status === 'A CONFIRMAR' ? 'status-pill pending' : item.status === 'CANCELADO' ? 'status-pill cancelled' : 'status-pill'}>{item.status}</span></td><td><div className="table-actions"><Link className="button-link" href={`/admin/agenda/${item.id}`}>Editar <ArrowUpRight size={14} /></Link><form className="inline-form" action={toggleAgendaAction}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="enabled" value={String(!item.enabled)} /><button className="secondary-button" type="submit">{item.enabled ? 'Ocultar' : 'Exibir'}</button></form><form className="inline-form" action={deleteAgendaAction}><input type="hidden" name="id" value={item.id} /><ConfirmSubmit><Trash2 size={14} /></ConfirmSubmit></form></div></td></tr>)}</tbody></table></section></div></>;
}
