import Link from 'next/link';
import { ArrowUpRight, Plus, Trash2 } from 'lucide-react';
import { deleteEventAction, saveSectionAction, toggleEventAction } from '@/app/admin/actions';
import { ConfirmSubmit } from '@/components/admin/ConfirmSubmit';
import { StorageUsage } from '@/components/admin/StorageUsage';
import { db } from '@/lib/db';

export default async function EventsAdminPage({ searchParams }: { searchParams: Promise<{ saved?: string }> }) {
  const [items, section, params, mediaUsage] = await Promise.all([db.recentEvent.findMany({ orderBy: { position: 'asc' } }), db.sectionSettings.findUniqueOrThrow({ where: { section: 'events' } }), searchParams, db.media.aggregate({ _sum: { size: true } })]);
  return <><header className="admin-topbar"><div><h1>Ultimos eventos</h1><p>Gerencie os registros visuais da home.</p></div><Link className="primary-button" href="/admin/eventos/new"><Plus size={16} /> Novo evento</Link></header><div className="admin-content">{params.saved ? <div className="flash">Alteracoes salvas com sucesso.</div> : null}<StorageUsage usedBytes={mediaUsage._sum.size ?? 0} /><form action={saveSectionAction} className="admin-card"><input type="hidden" name="section" value="events" /><div className="admin-card-header"><div><h2>Texto da secao</h2><p>O layout da galeria e fixo pelo design master.</p></div></div><div className="form-grid three"><div className="field"><label>Titulo</label><input name="title" defaultValue={section.title} required /></div><div className="field"><label>Subtitulo</label><input name="subtitle" defaultValue={section.subtitle} required /></div><div className="field"><label>CTA</label><input name="cta" defaultValue={section.cta} required /></div></div><div className="form-actions"><button className="primary-button" type="submit">Salvar alteracoes</button></div></form><section className="admin-card admin-section"><div className="admin-card-header"><div><h2>Galeria de eventos</h2><p>{items.length} registros cadastrados.</p></div></div><table className="admin-table"><thead><tr><th>Imagem</th><th>Evento</th><th>Data</th><th>Status</th><th>Acoes</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><img src={item.coverImage} alt="" width={72} height={42} style={{ objectFit: 'cover', borderRadius: 4 }} /></td><td><strong>{item.title}</strong><small>{item.city} / {item.state}</small></td><td>{new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short', year: 'numeric' }).format(item.eventDate).replace('.', '')}</td><td><span className={item.enabled ? 'status-pill' : 'status-pill pending'}>{item.enabled ? 'ATIVO' : 'OCULTO'}</span></td><td><div className="table-actions"><Link className="button-link" href={`/admin/eventos/${item.id}`}>Editar <ArrowUpRight size={14} /></Link><form className="inline-form" action={toggleEventAction}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="enabled" value={String(!item.enabled)} /><button className="secondary-button" type="submit">{item.enabled ? 'Ocultar' : 'Exibir'}</button></form><form className="inline-form" action={deleteEventAction}><input type="hidden" name="id" value={item.id} /><ConfirmSubmit><Trash2 size={14} /></ConfirmSubmit></form></div></td></tr>)}</tbody></table></section></div></>;
}
