import Link from 'next/link';
import { ArrowUpRight, Plus, Trash2 } from 'lucide-react';
import { deleteSetAction, saveSectionAction, toggleSetAction } from '@/app/admin/actions';
import { ConfirmSubmit } from '@/components/admin/ConfirmSubmit';
import { db } from '@/lib/db';

export default async function SetsAdminPage({ searchParams }: { searchParams: Promise<{ saved?: string }> }) {
  const [items, section, params] = await Promise.all([db.setItem.findMany({ orderBy: { position: 'asc' } }), db.sectionSettings.findUniqueOrThrow({ where: { section: 'sets' } }), searchParams]);
  return <><header className="admin-topbar"><div><h1>SETs</h1><p>Gerencie os ultimos lancamentos exibidos no site.</p></div><Link className="primary-button" href="/admin/sets/new"><Plus size={16} /> Novo set</Link></header><div className="admin-content">{params.saved ? <div className="flash">Alteracoes salvas com sucesso.</div> : null}<form action={saveSectionAction} className="admin-card"><input type="hidden" name="section" value="sets" /><div className="admin-card-header"><div><h2>Texto da secao</h2><p>A home exibe ate tres itens compactos.</p></div></div><div className="form-grid three"><div className="field"><label>Titulo</label><input name="title" defaultValue={section.title} required /></div><div className="field"><label>Subtitulo</label><input name="subtitle" defaultValue={section.subtitle} required /></div><div className="field"><label>CTA</label><input name="cta" defaultValue={section.cta} required /></div></div><div className="form-actions"><button className="primary-button" type="submit">Salvar alteracoes</button></div></form><section className="admin-card admin-section"><div className="admin-card-header"><div><h2>Lista de sets</h2><p>{items.length} itens cadastrados.</p></div></div><table className="admin-table"><thead><tr><th>Capa</th><th>Titulo</th><th>Genero</th><th>Duracao</th><th>Status</th><th>Acoes</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><img src={item.coverImage} alt="" width={50} height={50} style={{ objectFit: 'cover', borderRadius: 4 }} /></td><td><strong>{item.title}</strong><small>{item.platform}</small></td><td>{item.genre}</td><td>{item.duration}</td><td><span className={item.enabled ? 'status-pill' : 'status-pill pending'}>{item.enabled ? 'ATIVO' : 'OCULTO'}</span></td><td><div className="table-actions"><Link className="button-link" href={`/admin/sets/${item.id}`}>Editar <ArrowUpRight size={14} /></Link><form className="inline-form" action={toggleSetAction}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="enabled" value={String(!item.enabled)} /><button className="secondary-button" type="submit">{item.enabled ? 'Ocultar' : 'Exibir'}</button></form><form className="inline-form" action={deleteSetAction}><input type="hidden" name="id" value={item.id} /><ConfirmSubmit><Trash2 size={14} /></ConfirmSubmit></form></div></td></tr>)}</tbody></table></section></div></>;
}
